### ISSUE TITLE
how to start up for lama

### ISSUE THREAD

**Issue by Psykas** [Zappatta/wremote#3]
Hi,
I got stuck with MQQT server, I tried io.adafruit.com but for me don't work. Can you explain more with examples how to configure everything?

**Comment by Zappatta** [comment]
Hey @Psykas thanks for reporting.

It seems that Adafruit.io uses a different port for their MQTT server. So I've modified the code to allow setting the port in the config.h file

Just pull the latest changes and modify the config.h file

The relevant part for you should be 
`
#define MQTT_SERVER    	"io.adafruit.com"
#define MQTT_USERNAME  	"YOUR_ADAFRUIT_IO_USER"
#define MQTT_PASS       "YOUR_ADAFRUIT_IO_KEY"
#define MQTT_PORT      1883
`
You can find Adafruit.io MQTT documentation [here](https://learn.adafruit.com/adafruit-io/mqtt-api). If you need any help feel free to ask.

**Comment by Psykas** [comment]
Thanks for information next week I'll continue on this project, and I think I will need more helps.

**Comment by Psykas** [comment]
Like I wrote before, I need more helps. Finally I connect to MQTT server, but I can't subscribe and publish values to the server. I mean for example I don't get "ambianceTemp" value into Adafruit MQTT feed.

**Comment by Zappatta** [comment]
Adafruit requires that MQTT topics you post to will have assigned feeds in the Adafruit.io management console. It is described [here](https://learn.adafruit.com/adafruit-io/mqtt-api#topics) in their documentation.

So what you want to do is create a feed named ambianceTemp. Then in your config.h file set the MQTT_SUBJECT param as the prefix of your topics. it should be  "<adafruit username>/feeds/"

then your board will post to ""<adafruit username>/feeds/ambianceTemp", which should be picked by adafruit.

**Comment by Psykas** [comment]
Thank You,  Maybe you know how to solve  this issue : 
 ets Jan  8 2013,rst cause:4, boot mode:(3,6)
wdt reset
load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v614f7c32
~ld

**Comment by Zappatta** [comment]
Not sure where you're getting that, but it looks like you are unable to upload the sketch to your board. Could be drivers, or selecting wrong port/board type in the Arduino IDE. 

I suggest trying to following:
1. Make sure you have all the drivers installed
2. Make sure you installed the board in the Arduino board manager
3. Make sure you have selected the correct board type in the Arduino IDE
4. Try a different USB port 
5. Try a different and good quality USB cable.

**Comment by Psykas** [comment]
No I get this fault in serial monitor when  Wemos D1 min chip tray to connect to MQTT server. Seems like make 3-5 loops and then restart again. Something like unstable connection. 

> WiFi
 connected
IP address: 
192.168.0.204
oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.
 ets Jan  8 2013,rst cause:4, boot mode:(1,6)

wdt reset

> 

I tried two chip and I got the same issue. In the same chip I uploaded mqtt_esp8266 example  from Adafuit Mqtt library and the example works fine .

**Comment by Zappatta** [comment]
That's weird. I've tried on WeMos D1 R1 but not D1 Mini. I will order one for testing but it will take a couple of weeks to get here.

In the meantime, WDT reset means your board freezes or enters some kind of infinite loop. There can be many reasons. Do you have anything connected to the board? Led? Temperature sensor? Can you post the schema? Even a picture would be cool. 

Have you tried running the sketch on a bare board? One that has nothing connected to it? does it still crash?

**Comment by Psykas** [comment]
today I tried WeMos D1, and I got the same issue and I tried running the sketch on bare board.
![img_20180721_115755](https://user-images.githubusercontent.com/41123768/43034080-e1e6b76c-8cdd-11e8-9d48-c6901692b055.jpg)
![img_20180721_115808](https://user-images.githubusercontent.com/41123768/43034081-e2032adc-8cdd-11e8-8ec5-9d0a6569b24f.jpg)

So something wrong with my stuff.

**Comment by Zappatta** [comment]
It's not the exact board I used but should be similar enough. Not sure why you are getting WDT resets. 

If you feel like trying to figure out where exactly does the code crash, [here is a nice guide](https://arduino-esp8266.readthedocs.io/en/latest/faq/a02-my-esp-crashes.html#check-where-the-code-crashes). 
It would help me immensely if you use this to figure out which line of code causes the crash. 

What MIGHT be a quick solution for you is to increase the WDT timeout. It should be possible to do by adding this your setup()

```
ESP.wdtDisable();
ESP.wdtEnable(WDTO_8S);
```
Let me know if there is anything else I can do to help.

**Comment by Psykas** [comment]
I found out that code crash when to start function 

>      sendTempratureUpdate();
> 
and exhactly line is where crash is 

> client.publish(strcat(MQTT_SUBJECT,"ambianceTemp"), cstr); 

> 
That means that my publish function restarting of the board. But why?

**Comment by Zappatta** [comment]
Hmm, just make sure it is indeed the publish, can you try publishing hard-coded strings?
Just change the line to 
```
client.publish("test_topic", "test payload");
```
and see if it still crashes? 
You've also mentioned that you tried using the MQTT example, and it ran without crashing.
Was it this example? 

https://github.com/knolleary/pubsubclient/blob/master/examples/mqtt_esp8266/mqtt_esp8266.ino

If not, can you try that one?
I am curious if it happens with ANY mqtt publish, or just that one specifically.

**Comment by Psykas** [comment]
No I using this example : [https://github.com/adafruit/Adafruit_MQTT_Library/blob/master/examples/mqtt_esp8266/mqtt_esp8266.ino](url) 
and it ran without crashing and I can subscribe and publish values to the server. So right now I'm trying adapt your code to adafruit_MQTT_Library, but in this time crashing line is

>       int power = atoi(strtok(cmdBuf, comma)); 
> 
maybe I send bad value from MQTT server I don't know. For example if I want to turn on air conditioner what code I should sent  from MQTT server?

mqtt_esp8266.ino example from PubSubClient.h library  looks like didn't crash but I can't subscribe and publish values to the server, maybe I made wrong configuration.

**Comment by Psykas** [comment]
did you tried pubsubcient.h library for io.adafruit.com MQTT server?

**Comment by Zappatta** [comment]
I did not try Adafruit's MQTT library. 

But I did try the pubsubclient MQTT library with Adafruit and with this project's sketch. So I don't think the problem is the MQTT client <--> Adafruit server mismatch.

If you want to control the AC just call the executeCommand function with a string containing 4 comma separated values. for example "1, 1, 26, 0" ( should turn the AC on, cooling mode, 26c, automatic fan)

But If this is a problem that may affect other people I would like to know so I can modify the code to be compatible with more boards. 

Anyways, if you wish we can do a call / screen share session to help and pinpoint the cause for the crashes. Just email me and we'll find a suitable time. My email address is my github username at gmail.

**Comment by Psykas** [comment]
finally I found what caused a conflict on wemos bord in my case. This is strtok  command, I don't know why it's happening but for example  when I changed  line

> topic, strcat(MQTT_SUBJECT,"set")

> 
by 

> (topic, "psykas7777/feeds/set") 

> 
 the board stop crashing  and now I can get data from MQTT server but now crashing in this line 

>     int power = atoi(strtok(cmdBuf, comma)); 

so how I can avoid  strtok  command in the code ?

**Comment by Zappatta** [comment]
Could it be that you are using an old version of ESP8266 Core for arduino?
I'm seeing this issue: https://github.com/esp8266/Arduino/issues/352

But it was merged a long time ago. Can you try making sure you are using
the latest version in your Arduino IDE boards manager?

**Comment by Psykas** [comment]
I used latest version. 
![image](https://user-images.githubusercontent.com/41123768/43045731-f036831c-8dc6-11e8-8477-325b1dc214b2.png)

**Comment by Zappatta** [comment]
That is the latest version indeed. So I think strtok should work. Perhaps
it is crashing because it is receiving  unexpected data?

Can you do
Serial.println(cmdBuf) right before calling strtok so we can make sure it's
getting an expected value?

**Comment by Psykas** [comment]
You was right it is crashing because receiving unexpected data.  So I fixed it and today I tried it and it works :) Thank You for your help. So I move forward step by step :)
Can you give me some tips how to make something like you made 
![image](https://user-images.githubusercontent.com/41123768/43074735-f5ab1e14-8e86-11e8-8b49-1b35a866c65e.png)

**Comment by Zappatta** [comment]
Very glad to hear you got it working. Glad I could help with that :)

There are several online tools and phone apps that let you create MQTT flows and dashboards. [Here is a nice list.](http://www.steves-internet-guide.com/iot-mqtt-dashboards/)

However, you can (and encouraged) to use exactly what I made. The source code is available in this repository, with installation instructions [here](https://github.com/Zappatta/wremote/tree/master/server). 

There is also a docker image that you can use.

But it is intended to be self-hosted.

To keep it online 24/7 and accessible from the internet you will need a server. You can rent one for as cheap as a few $ a month.  Or you can use one on your computer and do port-forwarding in your router. There are even services that let you run managed docker containers, which is a bit more expensive but easier to set.

**Comment by Psykas** [comment]
I have raspberry pi with owncloud and NAS server witch is online 24/7. In the future I have a plan to buy new raspberry pi only for home automation. 
I read all your files, but for me is too much new things and too difficult everything understand.

**Comment by Zappatta** [comment]
It's actually quite simple to set up, but indeed requires minimal
javascript knowledge.

You can try some apps or online dashboard services. Just search the
app/play store for "MQTT dashboard".

You can also always send MQTT commands using Adafruit's web interface.

Best of luck!!

**Comment by Psykas** [comment]
I found same interesting tools for create dashboard on the phone thank you for help.  But I  have more questions can I sent only one value for example only change mode or increase temperature. Right now I sent  all "1, 24, 1, 0" data string, but if I need only change mode  can I send only mode value 3 . I tried  this code below but it just turn off the air condition. I don't know how exactly wok tadiran library. 

```
void mqttCallback(char* topic, byte* payload, unsigned int length) {
  Serial.print("Message arrived [");
  Serial.print(topic);
  Serial.print("] ");
  Serial.println();
  
  char strPayload[length +1];
  strPayload[length] = '\0';
  for(int i=0;i<length;i++){
    strPayload[i] = payload[i];
  }

  if(strcmp(topic, "psykas7777/feeds/set") == 0){
    executeCommand(String(strPayload));
  }

    if(strcmp(topic, "psykas7777/feeds/mode") == 0){
    executeCommandmode1(String(strPayload));
  }
}
void executeCommandmode1(String command){
     IRsend irsend(IR_LED_PIN);    
    Tadiran tadiran(1, 1, 26, 0);
    char* comma = ",";
        char cmdBuf[50];
    command.toCharArray(cmdBuf, 50);
      int acMode = atoi(cmdBuf);
      tadiran.setMode(acMode);
    irsend.sendRaw(tadiran.codes, TADIRAN_BUFFER_SIZE, 38);
    delay(500);
    irsend.sendRaw(tadiran.codes, TADIRAN_BUFFER_SIZE, 38);
    delay(500);
    irsend.sendRaw(tadiran.codes, TADIRAN_BUFFER_SIZE, 38);
    //send 3 times to decrease chances of AC not getting msg
    Serial.println("Executed command mode");    
}
void executeCommand(String command){
  
    IRsend irsend(IR_LED_PIN);    
    Tadiran tadiran(1, 1, 26, 0);
    char* comma = ",";
        char cmdBuf[50];
    command.toCharArray(cmdBuf, 50);
    int power = atoi(strtok(cmdBuf, comma));
    int temp = atoi(strtok(NULL, comma));
    int acMode = atoi(strtok(NULL, comma));
    int fan = atoi(strtok(NULL, comma));
        
    tadiran.setMode(acMode);
    tadiran.setTemeprature(temp);
    tadiran.setFan(fan);
    tadiran.setState(power);

    irsend.sendRaw(tadiran.codes, TADIRAN_BUFFER_SIZE, 38);
    delay(500);
    irsend.sendRaw(tadiran.codes, TADIRAN_BUFFER_SIZE, 38);
    delay(500);
    irsend.sendRaw(tadiran.codes, TADIRAN_BUFFER_SIZE, 38);
    //send 3 times to decrease chances of AC not getting msg

    Serial.println("Executed command set");    
}
```

**Comment by Zappatta** [comment]
AIr conditioner remotes work a bit weird and different from other remotes.
Every time you press a button, the remote doesn't just send that command.
It sends the entire state to the remote.

So for example, if you lower the temperature by one degree from 26c to 25c,
the remote doesn't send "lower degree by one" or even "set temperature to
25". It tells it "You need to be on, temperature needs to be 25, the fan
speed should be 3, and your mode should be *cooling*".

And since you send a state, you need to maintain that state somewhere. I've
opted for maintaining that state in the dashboard and keep the micro
controller "dumb". There are two reasons for that. First, I suck at C and
C++. Second, it is better maintain the state in one place and not two.
Because when you have two places where you store the state, you are prone
to having state mismatches. For example, what happens if your micro
controller loses power? it only has volatile memory and will forget what
state it previously had. You are better off avoiding this complication.

But if you really want to, you can have variables that store the parameters
of the state, then change it with separate MQTT topics and functions for
each of the state parameters. then send everything to the AC via the IR.

But I strongly recommend you find a way to do that in your dashboard and
not in the micro controller code.
